name: Bug report
description: Submit a bug report
body:
  - type: markdown
    attributes:
      value: |
        👉 Please provide the output of the console command `backintime --diagnostics`, to help us diagnose the problem quickly.
        👉 Please specify as precisely as you can the package or installation source where you got _Back In Time_ from.
        👉 As an **alternative** fell free to use our [mailing list](https://mail.python.org/mailman3/lists/bit-dev.python.org) for every topic about _Back In Time_.
  - type: textarea
    attributes:
      label: "Describe the problem, feature or ask a question:"
      description: "Please remember that this project is maintained by volunteers in their free time – human beings just like you – so we kindly ask for your understanding and constructive feedback as we work to address reported issues."

